baseURL = 'http://www.meegada.in/'
#baseURL= 'https://kolluruss.github.io/'
languageCode = 'en-us'
title = 'Dr. Meegada RamalingaSwamy'
theme = 'relearn'

[params]
  themeVariant = [ "meegada", "blue","red", "zen-dark", "relearn-light", "relearn-dark" ]

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]
